Added an option to specify target framework
stryker-mutator/stryker-net pull request #1684
Opened 2021-09-09 15:53 UTC by psfinaki

Okay so 1.0 is out and I want to address the biggest pain we have :D 

This implementation works but I haven't added tests yet as I want to verify if this the right direction and if this fits the new options approach.

![image](https://user-images.githubusercontent.com/5451366/132719861-45760062-a45e-4e4a-8aeb-3b430153f070.png)

If we merge this I will go try Stryker 1.0 in action!

2021-09-09 16:57 UTC, rouke-broersma commented
Do you think it will be something that can change run to run? If so a cli option is appropriate. If not there should only be a file based option.

I don't really know if people will want to run against both target frameworks or if they will generally pick one which will remain static (and should thus be in the config file).

I think you can best answer that question.

2021-09-09 17:28 UTC, rouke-broersma commented
Btw we released an rc for v1 but not v1 yet :p

2021-09-09 18:11 UTC, psfinaki commented
> Do you think it will be something that can change run to run? If so a cli option is appropriate. If not there should only be a file based option.

Hmm hard to say for sure but we at least will be running everything against .NET Core for now to simplify things so I imagine we'll specify this in the config. So probably we can start with that and maybe add the CLI option later.

We can also revise the whole thing once the support for runs against multiple frameworks is added - which should be cool but will need more thinking and effort to implement. We have already encountered one platform-specific mutation (for the same code) so there's potential in that topic :)

So I guess I'll remove the cli option and add tests & docs?

> Btw we released an rc for v1 but not v1 yet :p

Yeah but it's v1.0 code running and that's what matters :D

2021-09-10 11:20 UTC, richardwerkman requested changes
Thanks for your contribution :)

2021-09-10 16:41 UTC, psfinaki commented on src/Stryker.Core/Stryker.Core/Options/Inputs/TargetFrameworkInput.cs
> +                    throw new InputException("Target framework cannot be empty. Please provide a valid value from this list: https://docs.microsoft.com/en-us/dotnet/standard/frameworks");
Well I thought about it but the list is quite long and there also are weird things there like `net6.0-ios14.0` and so on. Plus it's not very futureproof anyway... I haven't found examples for a proper approach around as well.

2021-09-10 16:42 UTC, psfinaki commented on src/Stryker.CLI/Stryker.CLI/CommandLineConfigHandler.cs
> +            AddCliInput(inputs.TargetFrameworkInput, "target-framework", "t", CommandOptionType.SingleValue);
Will do this and add tests, hang on

2021-09-13 16:11 UTC, psfinaki commented on src/Stryker.CLI/Stryker.CLI/CommandLineConfigHandler.cs
> +            AddCliInput(inputs.TargetFrameworkInput, "target-framework", "t", CommandOptionType.SingleValue);
Right, so this is moved

2021-09-13 16:13 UTC, psfinaki commented on src/Stryker.Core/Stryker.Core/Initialisation/ProjectFileReader.cs
> +            var analyzerResultForFramework = analyzerResults.SingleOrDefault(result => result.TargetFramework == targetFramework);
Easier said than done... But it's there :) Not the most beautiful way probably. I started refactoring things a bit in the DI direction but got into a rabbit hole so stopped at the current implementation.

2021-09-13 16:13 UTC, psfinaki commented on src/Stryker.Core/Stryker.Core/Options/Inputs/TargetFrameworkInput.cs
> +    public class TargetFrameworkInput : Input<string>
Added tests.

2021-09-13 16:14 UTC, psfinaki commented on src/Stryker.Core/Stryker.Core/Options/Inputs/TargetFrameworkInput.cs
> +                    throw new InputException("Target framework cannot be empty. Please provide a valid value from this list: https://docs.microsoft.com/en-us/dotnet/standard/frameworks");
Reopen if you have any ideas.

2021-09-14 14:40 UTC, psfinaki commented
@richardwerkman I hope I've addressed the points, please rereview :)

2021-09-16 14:58 UTC, richardwerkman approved these changes
Looking good! Found only some minor shouldly improvements still.

2021-09-16 14:58 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/TargetFrameworkResolutionTests.cs
> +            Assert.Equal("X", result.TargetFramework);
```suggestion
            result.TargetFramework.ShouldBe("X");
```

2021-09-16 14:58 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/TargetFrameworkResolutionTests.cs
> +            Assert.Equal("Y", result.TargetFramework);
```suggestion
            result.TargetFramework.ShouldBe("Y");
```

2021-09-16 14:58 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core.UnitTest/Initialisation/TargetFrameworkResolutionTests.cs
> +            Assert.Equal("X", result.TargetFramework);
```suggestion
            result.TargetFramework.ShouldBe("X");
```

2021-09-16 14:58 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core/Options/Inputs/TargetFrameworkInput.cs
> +                    throw new InputException("Target framework cannot be empty. Please provide a valid value from this list: https://docs.microsoft.com/en-us/dotnet/standard/frameworks");
We could use some sort of regex to check it. But it's very error prone indeed. For now let's keep it like this.

2021-09-16 16:02 UTC, psfinaki commented
Okay that was a pleasure to fix :D

2021-09-16 17:55 UTC, merged