feat(reporting): Report when a mutant is in a static context
stryker-mutator/stryker-net pull request #1820
Opened 2021-11-26 17:17 UTC by rouke-broersma

With this change you should be able to see in the json, html and dashboard reporter that a mutation is in a static context

Also introduce some files to be able to display test information later on
Related to #1565

2021-12-10 17:40 UTC, richardwerkman requested changes
Missing two tests :)

2021-12-10 17:40 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/TestProjects/TestCaseTests.cs
> +        public void TestCaseEquals()
```suggestion
        public void TestCasesWithEqualValuesShouldBeEqual()
```

2021-12-10 17:40 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/TestProjects/TestFileTests.cs
> +    public class TestFileTests
I'm missing tests for the Equality compare

2021-12-10 17:40 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/TestProjects/TestFileTests.cs
> +        public void MergeTestFiles()
```suggestion
        public void TestFilePlusTestFileShouldMerge()
```

2021-12-10 17:40 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/TestProjects/TestProjectTests.cs
> +        public void TestProjectEquals()
```suggestion
        public void TestProjectsWithEqualValuesShouldBeEqual()
```

2021-12-10 17:40 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/TestProjects/TestProjectsInfoTests.cs
> +        public void MergeTestProjectsInfo()
```suggestion
        public void ProjectsInfoPlusProjectsInfoShouldMerge()
```

2021-12-10 17:40 UTC, richardwerkman commented on src/Stryker.Core/Stryker.Core.UnitTest/ProjectComponents/TestProjects/TestProjectsInfoTests.cs
> +    public class TestProjectsInfoTests
I miss a test for the equals operator here

2021-12-10 22:35 UTC, merged

2021-12-13 13:32 UTC, psfinaki commented
Hmm I'm trying to get my head around that to understand if this anyhow affects us. This doesn't affect numbers and scores, just adds a marker in the report, right?
<img width="373" alt="image" src="https://user-images.githubusercontent.com/5451366/145821560-79a7c1ac-bcc7-4252-991a-aa2490d29a4d.png">

2021-12-13 13:33 UTC, rouke-broersma commented
This just adds a marker in the report. There is behavior associated with this marker but that is not new.

2021-12-13 14:00 UTC, psfinaki commented
Alright, thanks!