Fix the problem that the test projects are not being enriched by VsTest.
stryker-mutator/stryker-net pull request #2751
Opened 2023-11-03 14:45 UTC by MischaVreeburg

For the enrichment, an alternative datasource has been chosen along with some clever parsing. It now falls back for C# files to the previously scanned test source files and tries to map the test full name with the name in the file and uses that info to get the test file path, along with the method declaration.

This PR fixes issue: https://github.com/stryker-mutator/stryker-net/issues/2750

2023-11-04 11:23 UTC, dupdob commented
Thanks for this PR. This is not a review but a bunch of general comments:
1) you need to add unit test for this. I suggest isolating the source code searching/parsing algorithm so writing test is easier
2) note that this approach provides only partial support: unit tests can be renamed via framework specific attributes and theory like tests may include data as part of their name.

Overall, I think this is a good move, but I would like feedback from the core team regarding if this is an approach they support (i.e. this simply improving and supporting it until a fix from VsTest teams is made available)

2023-11-24 18:32 UTC, rouke-broersma commented
@dupdob sounds good to me, I have no objection and I agree with your review feedback as well.

2024-07-24 15:25 UTC, dupdob requested changes
The test detection logic should be moved to a specific class, or methods.
You need to add unit tests for this

2024-07-24 15:25 UTC, dupdob commented on src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs
>                  }
Could be please move this logic to a dedicated class ? at least dedicated methods?

This code needs unit tests.

2026-08-25 09:51 UTC, dupdob commented
Closing as PR is abandoned

2026-08-25 09:51 UTC, closed without merging